C:\DOS\SMARTDRV.EXE
@ECHO OFF
PROMPT $p$g
PATH C:\DOS;C:\TC\BIN;C:\NORTON
PATH C:\NU;%PATH%
SET SYMANTEC=C:\SYMANTEC
SET NU=C:\NU
SET TEMP=C:\DOS
set DPMIMEM=MAXMEM 1000
set wcr_dat=c:\WCRC\DAT
CD\WCRC\EXE
 wit2
C:\NU\NDD C:/Q
C:\NU\IMAGE C:
